apiVersion: v1
kind: Pod
metadata:
  name: logi
  namespace: default
spec:
  containers:
  - image: busybox
    name: logi
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
    - name: scratch-volume
      persistentVolumeClaim:
        claimName: myclaim
