apiVersion: v1
kind: Pod
metadata:
  name: logi
  namespace: default
spec:
  containers:
  - image: busybox
    name: logi
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /opt
      name: nfs-vol
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: pvc-one
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
