kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvvol-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: cp-0
    readOnly: false
