apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-conf
data:
  nginx.conf: |
    # nginx.conf
         server {
             listen 80;
             server_name example.com

             location / {
                 root /usr/share/nginx/html;
                 index index.html;
             }
