apiVersion: v1
kind: Pod
metadata:
  name: alexa
  namespace: default
spec:
  containers:
  - image: busybox
    name: alexa
    command:
    - sleep
    - "3600"
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql
            key: password
