apiVersion: v1
kind: Pod
metadata:
  name: samsung
  namespace: default
spec:
  containers:
  - image: busybox
    name: samsung
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /mysqlpassword
      name: mysql
  volumes:
    - name: mysql
      secret:
        secretName: mysql
