apiVersion: v1
kind: Pod
metadata:
  name: chillibeans
  namespace: default
spec:
  containers:
  - image: busybox
    name: chillibeans
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir: {}
