# Question 19 - Pré-Req
#k create secret generic secret2 --namespace secret --from-literal=user=user1 --from-literal=pass=1234
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
  namespace: secret
spec:
  containers:
  - image: busybox:1.31.1
    name: secret-pod
    resources: {}
    volumeMounts:
    - name: secret1
      mountPath: "/tmp/secret1"
      readOnly: true
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secret2
          key: pass
    #command: ['sh','-c','sleep 360']
    args:
      - sh
      - -c
      - sleep 1d 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: secret1
      secret:
        secretName: secret1
        optional: true
status: {}
