apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-am-i-ready
  name: service-am-i-ready
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: am-i-ready
  type: ClusterIP
status:
  loadBalancer: {}
